### PR TITLE
Add function for get ManufacturerData and AdvertisingData with more tests

### PR DESCRIPTION
**Pull request by maxsimych**
Hello, it is the same PR #53 , but with added unit tests, as it was requested in the comment

              Hello, thanks for this useful PR. Can you integrate it with some unit tests. 

_Originally posted by @chrvadala in https://github.com/chrvadala/node-ble/pull/53#pullrequestreview-1284036695_

### CODE REVIEW

**Comment by gmacario** [comment]
Hello @chrvadala,

Any chances to have this PR reviewed and possibly merged into your repo?

Thanks in advance!
CC: @Raffone17

**Comment by chrvadala** [comment]
@gmacario I reviewed the original PR https://github.com/chrvadala/node-ble/pull/53. 
If you prefer to continue here, we can close the old one start from here.

**Comment by Raffone17** [comment]
@chrvadala we can continue from here.

**Comment by chrvadala** [comment]
That's fine, I'm going to close the other PR. Anyway, I commented your code there and I see that same requests apply here. Can you review your code? Thanks

**Review by chrvadala — CHANGES_REQUESTED** [review]
Waiting changes as commented here https://github.com/chrvadala/node-ble/pull/53

**Comment by chrvadala** [comment]
Superseed by #67

**Comment by chrvadala** [comment]
Released with 1.11

**Pull request closed without merging**
