### PR TITLE
Added typescript definition, corrected README

### PR DESCRIPTION
**Pull request by pascalopitz**

### CODE REVIEW

**Comment by pascalopitz** [comment]
No worries. Good work on the lib, works a treat!

**Comment by chrvadala** [comment]
Thank you, I'll merge soon

**Comment by Sunoo** [comment]
Just a quick note, spotted a few mismatches between this type definition and the library, and I corrected them in a pull request on that fork: https://github.com/pascalopitz/node-ble/pull/1

Might make sense to look into that before merging.

**Comment by jordanorc** [comment]
Any update on that?

**Comment by chrvadala** [comment]
Released with v1.3.0
Thanks @pascalopitz for the PR

**Comment by jordanorc** [comment]
Thank's @chrvadala and @pascalopitz! Great work :)

**Pull request merged**
